### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by christophwitzko** [christophwitzko/masters-thesis#20]
- [x] longer description for figures and tables
- [x] execution duration/time
- [x] polish conclusion
- [x] check bib
- [x] translate abstract
- [x] cites in related work?
- [x] request duration(s)
- [x] check links
- [x] open source this repository
- [x] submit thesis 🎉
